# Generated by Django 4.0.2 on 2022-03-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfCarAcc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cg', models.TextField(blank=True, db_column='CG', null=True)),
                ('sum', models.IntegerField(blank=True, null=True)),
                ('ctop', models.IntegerField(blank=True, db_column='CtoP', null=True)),
                ('ctoc', models.IntegerField(blank=True, db_column='CtoC', null=True)),
                ('calone', models.IntegerField(blank=True, db_column='CAlone', null=True)),
                ('year_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inf_car_acc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfChildZone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gugun', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('sname', models.TextField(blank=True, null=True)),
                ('stype', models.TextField(blank=True, null=True)),
                ('year_code', models.IntegerField(blank=True, null=True)),
                ('sido', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inf_child_zone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfEleDisplay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sido', models.TextField(blank=True, null=True)),
                ('gugun', models.TextField(blank=True, null=True)),
                ('year_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inf_ele_display',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfPopulation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year_code', models.IntegerField(blank=True, null=True)),
                ('gugun', models.TextField(blank=True, null=True)),
                ('household', models.IntegerField(blank=True, null=True)),
                ('pop_sum', models.IntegerField(blank=True, null=True)),
                ('male', models.IntegerField(blank=True, null=True)),
                ('female', models.IntegerField(blank=True, null=True)),
                ('sumkor', models.IntegerField(blank=True, db_column='sumKor', null=True)),
                ('korm', models.IntegerField(blank=True, db_column='korM', null=True)),
                ('korf', models.IntegerField(blank=True, db_column='korF', null=True)),
                ('sumfor', models.IntegerField(blank=True, db_column='sumFor', null=True)),
                ('form', models.IntegerField(blank=True, db_column='forM', null=True)),
                ('forf', models.IntegerField(blank=True, db_column='forF', null=True)),
                ('houseperperson', models.FloatField(blank=True, db_column='HousePerPerson', null=True)),
                ('over65', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inf_population',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfSmartCross',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year_code', models.IntegerField(blank=True, null=True)),
                ('sido', models.TextField(blank=True, null=True)),
                ('gugun', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inf_smart_cross',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfSmartLamp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gugun', models.TextField(blank=True, null=True)),
                ('data_date', models.TextField(blank=True, null=True)),
                ('sido', models.TextField(blank=True, null=True)),
                ('year_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inf_smart_lamp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfSpeedBump',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sido', models.TextField(blank=True, null=True)),
                ('gugun', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('year_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inf_speed_bump',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfUnCamera',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sido', models.TextField(blank=True, null=True)),
                ('gugun', models.TextField(blank=True, null=True)),
                ('gubun', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('year_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inf_un_camera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfYellowcarpet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('year_code', models.IntegerField(blank=True, null=True)),
                ('sido', models.TextField(blank=True, null=True)),
                ('gugun', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inf_yellowcarpet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'year',
                'managed': False,
            },
        ),
    ]
